TQMPG/Controllers/KPIController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TQMPG.Models;

namespace TQMPG.Controllers
{
    public class KPIController : Controller
    {
        private TQMEntitiesModel db = new TQMEntitiesModel();

        // GET: KPI
        public ActionResult Index()
        {
            return View(db.KPIs.ToList());
        }

        // GET: KPI/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KPI kPI = db.KPIs.Find(id);
            if (kPI == null)
            {
                return HttpNotFound();
            }
            return View(kPI);
        }

        // GET: KPI/Create
        public ActionResult Create()
        {

            ViewBag.KPI_DeptID = new SelectList(db.KPI_Dept, "AutoID", "Dept_Name");
            return View();
        }

        // POST: KPI/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AutoID,KPI_DeptID,KPI1")] KPI kPI)
        {
            if (ModelState.IsValid)
            {
                //kPI.KPI_DeptID = Dept;
                db.KPIs.Add(kPI);

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kPI);
        }

        // GET: KPI/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KPI kPI = db.KPIs.Find(id);
            if (kPI == null)
            {
                return HttpNotFound();
            }

            return View(kPI);
        }

        // POST: KPI/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AutoID,KPI_DeptID,KPI1")] KPI kPI)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kPI).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kPI);
        }

        // GET: KPI/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KPI kPI = db.KPIs.Find(id);
            if (kPI == null)
            {
                return HttpNotFound();
            }
            return View(kPI);
        }

        // POST: KPI/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            KPI kPI = db.KPIs.Find(id);
            db.KPIs.Remove(kPI);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TQMPG/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TQM PLUS</title>
    <link href="http://adpgintranet2.web.analog.com/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <script src="http://adpgintranet2.web.analog.com/static/js/jquery.min.js"></script>
    <script src="http://adpgintranet2.web.analog.com/static/bootstrap/js/bootstrap.min.js"></script>
    <script src="http://adpgintranet2.web.analog.com/static/datatables/datatables.min.js"></script>
    <link src="http://adpgintranet2.web.analog.com/static/font-awesome/css/font-awesome.css">
    <link src="http://adpgintranet2.web.analog.com/static/font-awesome/css/all.css">
    <link src="http://adpgintranet2.web.analog.com/static/font-awesome/css/font-awesome.min.css">
    <link href="http://adpgintranet2.web.analog.com/static/datatables/datatables.min.css" rel="stylesheet">
    @Styles.Render("~/Content/Site.css")


    @{System.Security.Principal.WindowsIdentity identity = HttpContext.Current.Request.LogonUserIdentity; }


</head>


<body>
    <nav class="navbar navbar-dark navbar-expand-lg fixed-top portfolio-navbar gradient"
         style="background-image: url(&quot;none&quot;);background-color: #ffffff;">
        <div class="container-fluid">
            <a href="@Url.Action("Index", "Home")">
                <img src="~/Content/Images/tqmpluslogo.png" alt="" />
            </a>
            <button data-toggle="collapse" class="navbar-toggler" data-target="#navbarNav">
                <span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item" role="presentation">
                        <a href="http://adpgintranet2.web.analog.com" class="nav-link" style="color:black">My TQM</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        @Html.ActionLink("Start A Story", "Index", "StorySubmit", null, new { @class = "nav-link", style = "color:Black" })
                    </li>
                    <li class="nav-item" role="presentation">
                        <a href="http://adpgintranet2.web.analog.com" class="nav-link" style="color:black">Resources</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a href="http://adpgintranet2.web.analog.com" class="nav-link" style="color:black">Contact Us</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        @Html.ActionLink("About", "About", "Home", null, new { @class = "nav-link", style = "color:Black" })
                    </li>
                    <li class="nav-item dropdown">
                        <a class="dropdown-toggle nav-link" data-toggle="dropdown"
                           aria-expanded="false" href="#" style="color: rgb(0, 0, 0);">Forms</a>
                        <div class="dropdown-menu" role="menu">
                            @Html.ActionLink("Register Department KPI", "Index", "KPI_Dept", null, new { @class = "dropdown-item", style = "color:Black" })
                            @Html.ActionLink("Register KPI", "Index", "KPI", null, new { @class = "dropdown-item", style = "color:Black" })
                            @Html.ActionLink("Register Department Head", "Index", "Dept_Info", null, new { @class = "dropdown-item", style = "color:Black" })
                            @Html.ActionLink("DH Approval", "Index", "Approval", null, new { @class = "dropdown-item", style = "color:Black" })
                            @Html.ActionLink("Facilitator", "Facilitator", "Approval", null, new { @class = "dropdown-item", style = "color:Black" })
                            @Html.ActionLink("Upload Completed Story", "UploadFile", "Upload", null, new { @class = "dropdown-item", style = "color:Black" })
                            @Html.ActionLink("Download Completed Story", "downloadFile", "Upload", null, new { @class = "dropdown-item", style = "color:Black" })
                        </div>
                       
                    </li>
                    <li class="nav-item" role="presentation">
                        <a href="#" class="nav-link" style="color:black">@identity.Name.Split('\\')[1]</a>
                    </li>


                </ul>
            </div>
        </div>
    </nav>


    <div class="container-fluid body-content" style="padding-top:50px;">
        @RenderBody()
        <hr />
        <footer>
            <p>@DateTime.Now.Year - Developed by ADPG MIS [1295]</p>
        </footer>
    </div>

</body>
</html>